import { Package, Deck, DeckConfig, Model, Note } from "ankipack";
import type { SqlJsStatic } from "sql.js";
import type { FlashcardSet } from "./types";
import { MediaIndex, flashcardToFields } from "./anki-fields";
import { downloadMedia, type DownloadProgress } from "./anki-media";

import {
  card1Front,
  card1Back,
  card2Front,
  card2Back,
  card3Front,
  card3Back,
  card4Front,
  card4Back,
  styling,
} from "./anki-templates";

// ── Notetype field & template definitions (shared between flip + typing models) ─

const FIELDS = [
  { name: "Term" },
  { name: "Definition" },
  { name: "TermImage", description: "Auto-generated by QuickCards." },
  { name: "TermAudio", description: "User-recorded audio (when available)." },
  { name: "TermTTS", description: "Quizlet auto-generated text-to-speech." },
  { name: "TermLang", plainText: true },
  { name: "DefinitionImage" },
  { name: "DefinitionAudio" },
  { name: "DefinitionTTS" },
  { name: "DefinitionLang", plainText: true },
  {
    name: "AddReverse",
    description: 'Set to "1" to generate the reverse card; clear to suppress.',
    plainText: true,
  },
  {
    name: "QuizletId",
    description: "Stable Quizlet card ID. Used for re-import dedup. Don't edit.",
    plainText: true,
  },
];

// ── FSRS preset tuning ────────────────────────────────────────────────────

/**
 * Build a DeckConfig tuned to the remaining deadline.
 * - `days`: days until the user needs to know the set (>= 1)
 * - `totalCards`: used as newPerDay so Anki doesn't throttle intro of new cards
 * - `isTyping`: typing decks run with slightly lower desired retention
 */
function buildConfig(
  days: number,
  totalCards: number,
  isTyping: boolean,
  name: string,
): DeckConfig {
  const baseDR = Math.min(0.95, Math.max(0.9, 0.9 + (14 - days) * 0.005));
  const desiredRetention = isTyping ? Math.max(0.8, baseDR - 0.05) : baseDR;

  let learnSteps: number[];
  let graduatingIntervalGood: number;
  let graduatingIntervalEasy: number;
  if (days <= 4) {
    learnSteps = [1, 5, 10, 30, 60];
    graduatingIntervalGood = 1;
    graduatingIntervalEasy = 2;
  } else if (days <= 7) {
    learnSteps = [1, 5, 10, 30];
    graduatingIntervalGood = 1;
    graduatingIntervalEasy = 2;
  } else {
    learnSteps = [1, 10];
    graduatingIntervalGood = 1;
    graduatingIntervalEasy = 4;
  }

  return new DeckConfig({
    name,
    desiredRetention,
    learnSteps,
    graduatingIntervalGood,
    graduatingIntervalEasy,
    newPerDay: Math.max(1, totalCards),
    reviewsPerDay: 9999,
    maximumReviewInterval: days,
    buryNew: true,
    buryReviews: true,
    reviewOrder: "retrievabilityAscending",
    newMix: "mixWithReviews",
    leechAction: "tagOnly",
  });
}

// ── Public API ────────────────────────────────────────────────────────────

export interface AnkiExportOptions {
  set: FlashcardSet;
  /** Days until the user needs to know the set. Used to tune the FSRS preset. */
  days: number;
  /** Initialized sql.js instance. */
  SQL: SqlJsStatic;
  /**
   * When false, no DeckConfig is attached and ankipack lets each deck fall
   * back to a minimal auto-generated preset. The user can then assign their
   * own preset in Anki. When true (default), we ship a deadline-tuned preset.
   */
  withPreset?: boolean;
  /** Called after each media download and once when the build phase begins. */
  onProgress?: (progress: DownloadProgress) => void;
}

/**
 * Build an .apkg with two decks rooted on the QuickCards v1 notetype family:
 *   - `<title>` — flip cards (Term ↔ Definition), 2 cards per note
 *   - `<title> (Typing)` — typing variants, up to 2 cards per note (skipped
 *     when the typed-side text is empty, e.g. image-only Quizlet cards)
 *
 * Media (images, user audio, Quizlet TTS) is downloaded in parallel from the
 * extension's background context, which carries the user's Quizlet cookies
 * so authenticated TTS URLs resolve. Failed downloads are skipped silently.
 */
export async function buildAnkiPackage(opts: AnkiExportOptions): Promise<Uint8Array> {
  const { set, days, SQL, withPreset = true, onProgress } = opts;
  const title = set.title || "QuickCards";
  const totalCards = set.cards.length;

  // 1. Map every flashcard onto the 12-field shape, recording every distinct
  //    media URL into the index along the way.
  const media = new MediaIndex();
  const noteFields = set.cards.map((c) => flashcardToFields(c, media));

  // 2. Download all referenced media in parallel. No-op when the index is
  //    empty (e.g. plain text-only flashcards).
  const fileMap = await downloadMedia(media.entries(), onProgress);

  // 3. Signal the start of the (synchronous) packaging phase.
  onProgress?.({ phase: "build", done: 0, total: 0, failed: 0 });

  // 4. Build the two notetypes. They share the field set; only their template
  //    list differs (flip vs typing).
  const flipModel = new Model({
    name: "QuickCards v1",
    css: styling,
    sortFieldIndex: 0,
    fields: FIELDS,
    templates: [
      { name: "Term → Definition", questionFormat: card1Front, answerFormat: card1Back },
      { name: "Definition → Term", questionFormat: card2Front, answerFormat: card2Back },
    ],
  });

  const typingModel = new Model({
    name: "QuickCards Typing v1",
    css: styling,
    sortFieldIndex: 0,
    fields: FIELDS,
    templates: [
      { name: "Type Term → Definition", questionFormat: card3Front, answerFormat: card3Back },
      { name: "Type Definition → Term", questionFormat: card4Front, answerFormat: card4Back },
    ],
  });

  // 5. Build the decks. With a preset, each deck gets a deadline-aware
  //    DeckConfig. Without (config undefined), ankipack ships no per-deck
  //    deck_config row and points the deck's config_id at Anki's built-in
  //    default preset (id=1), so nothing new appears in the user's preset
  //    list.
  const flipDeck = new Deck({
    name: title,
    config: withPreset
      ? buildConfig(days, totalCards, false, `QuickCards · ${title} (${days}d)`)
      : undefined,
  });
  const typingDeck = new Deck({
    name: `${title} (Typing)`,
    config: withPreset
      ? buildConfig(days, totalCards, true, `QuickCards · ${title} (${days}d, typing)`)
      : undefined,
  });

  // 6. Add notes. Same field values to both decks; the differing notetype
  //    decides which templates render.
  for (const fields of noteFields) {
    flipDeck.addNote(new Note({ model: flipModel, fields }));
    typingDeck.addNote(new Note({ model: typingModel, fields }));
  }

  // 7. Pack and bundle.
  const pkg = new Package();
  pkg.addDeck(flipDeck);
  pkg.addDeck(typingDeck);
  for (const [filename, bytes] of fileMap) {
    pkg.addMedia(filename, bytes);
  }

  return pkg.toUint8Array(SQL);
}
